version: '3.4'

services:
  
  webapi:
    container_name: webapi
    build:
      context: material
      dockerfile: WebApi/Dockerfile    
    ports:
      - 8081:80
    environment: 
      - AppSettings__Variable="This is from Docker" 
    depends_on: 
    - db-sql-server
  
  webapp:
    container_name: webapp
    build:
      context: material
      dockerfile: WebApp/Dockerfile
    environment: 
      - ServerUrl=http://webapi:80/api/
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 80:80
    depends_on: 
      - webapi

  db-sql-server:
    container_name: db-sql-server
    image: stvansolano/adventure-works-sql-server:latest
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"


  play-with-docker:
    container_name: play-with-docker
    image: docker/getting-started:pwd
    ports:
      - 8080:80