version: '3.4'

services:
  
  emarket_api:
    container_name: emarket_api
    build:
      context: ./
      dockerfile: Dockerfile.api    
    ports:
      - 4000:80
    depends_on: 
    - emarket_db
  
  emarket_app:
    container_name: emarket_app
    build:
      context: ./
      dockerfile: Dockerfile.app
    environment: 
      - ServerUrl=http://emarket_api:80/api/
    ports:
      - 5000:80
    depends_on: 
      - emarket_api

  emarket_db:
    container_name: emarket_db
    image: luiseav/emarketdb:latest
    ports:
      - 1410:1433
    environment:
      SA_PASSWORD: "Password.123"
      ACCEPT_EULA: "Y"